### PR TITLE
Update Demo labeling to Studio Training

### PR DESCRIPTION
**Pull request by AJDurant**

### CODE REVIEW

**Comment by wlcx** [comment]
Is 'demo' being kept as internal parlance for module names/urls? Worth changing them too?

**Comment by Flump5281** [comment]
Not worth the effort changing configs and database things for that.

Besides, this is one of the features I want to remove anyway, as it's actually entirely a hack.

**Comment by AJDurant** [comment]
Yeah, this was just a quick re-nameing thing, at some point it will be completely re-worked, but for now it is just frontend

**Comment by Flump5281** [comment]
Should possibly consistently use Session or Slot?

**Comment by AJDurant** [comment]
I wondered that, but was mostly happy with the wording

**Pull request merged**
