### PR TITLE
Other stuff from #682

### PR DESCRIPTION
**Pull request by LordAro**

### CODE REVIEW

**Comment by AJDurant** [comment]
Not reloading the page was deliberate, that is why there was preventDefault. These calls were for AJAX requests, the page display should have reacted itself.

**Comment by LordAro** [comment]
Hrm, OK. How is the page display supposed to react?

**Comment by AJDurant** [comment]
It entirely depends on what the action is. If you are revoking permissions for example then the permission element in the list should be removed from the page.

**Comment by LordAro** [comment]
OK, removed for now, will work it out later

**Pull request merged**
