### PR TITLE
Re-Implement OBIT to play from Playlist

### PR DESCRIPTION
**Pull request by mstratford**
- [x] Disabling single file played still needs to be done.

### CODE REVIEW

**Comment by mstratford** [comment]
The only issue I could see with doing this, is that Jukebox could potentially resort to it's internal default playlists if MyRadio were lost during OBIT time?

**Comment by adfw** [comment]
I'd be inclined to agree with that risk there -- you ideally want it to be as failure-proof as possible. Also, in its current state, would this permit manual track requests to be queued, effectively inserting stuff into the Obit playlist?

**Comment by mstratford** [comment]
Hmm, yes, potentially people could request files, hmm. I could of course disable the request form during OBIT

**Comment by LordAro** [comment]
Aside: Obit is not an acronym - shorthand for obituary

**Comment by markspolakovs** [comment]
As discussed IRL, not only are there the issues above (requests and myradio outages), there's also the risk of playing inappropriate jingles ("WHEN WE'RE ALL OUT LIVING OUR LIVES, HAVING FUN..." isn't great during a royal death). I think the most failure-proof solution is to have Jukebox switch to an "obit mode", where it only plays suitable music (either from MyRadio or a local backup file) and only plays suitable jingles (read as: callsign and nothing else).

**Comment by markspolakovs** [comment]
Old PR, and unworkable for reasons listed above, closing.

**Pull request closed without merging**
