### PR TITLE
Development Dockerfile

### PR DESCRIPTION
**Pull request by markspolakovs**

### CODE REVIEW

**Comment by mstratford** [comment]
Is this ready to review? :)

**Comment by markspolakovs** [comment]
In theory

**Comment by markspolakovs** [comment]
Eh, good enough, we can always iterate

**Comment by cs-499243** [comment]
```
Config::$short_name = 'URN';
Config::$long_name = 'University Radio Nork';
```
Very nice

Also is this going to be sure to use the right postgres version? Just asking cause bootstrap.sh is explicit about it

**Comment by markspolakovs** [comment]
> Also is this going to be sure to use the right postgres version? Just asking cause bootstrap.sh is explicit about it

It’ll use whichever is tagged as latest on https://hub.docker.com/_/postgres, which right now is 14… so we might want to pin it to a Postgres major at least.

**Pull request merged**
