### PR TITLE
expose nipsweb item

### PR DESCRIPTION
**Pull request by michael-grace**
marks is going to complain that i haven't graphqlanised it

### CODE REVIEW

**Comment by markspolakovs** [comment]
y

**Comment by michael-grace** [comment]
z

**Comment by michael-grace** [comment]
in seriousness, regarding making current "bad autoplayout" and probable "future better one" get managed item usefullness (i mean, atm the path)

**Comment by markspolakovs** [comment]
Fair enough. Does this also account for managed playlists?

**Review by markspolakovs — APPROVED** [review]
Hm, interesting that review-machine didn't run. Oh well.

**Pull request merged**
