### PR TITLE
Use is_in_byline to generate presenter string.

### PR DESCRIPTION
**Pull request by mstratford**
This allows co-presenters (and others, as specified in the credits db table) to appear in the presenters string used by radioplayer etc. Replaces #800.

### CODE REVIEW

**Comment by URY-GitHub** [comment]
Thank you for this pull request, @mstratford!

@SplashyFish14, would you mind reviewing this PR, please? Feel free to ask anyone for help if you're not quite sure what you're doing.

**Comment by markspolakovs** [comment]
I will note that currently Presenter is the only credit_type with is_in_byline set... but this is a good change nonetheless

**Comment by mstratford** [comment]
Indeed, currently trying to test it.

**Comment by mstratford** [comment]
Ready 👍 Tested on Dev.

**Comment by mstratford** [comment]
> I will note that currently Presenter is the only credit_type with is_in_byline set... but this is a good change nonetheless

I've just added Co-Presenters, which was the original issue.

**Pull request merged**
