### PR TITLE
Support Links

### PR DESCRIPTION
**Pull request by michael-grace**

### CODE REVIEW

**Review by markspolakovs — APPROVED** [review]
Pulled into staging, and it does work (once I added in a GLOBAL_ACCESS permission) - I hate the fact that you used tabledata, but it is effective (though I'm not sure we want there to be a search bar on a page with six entries...)

**Comment by michael-grace** [comment]
my plan was to put a no login auth on it, just cause we want the sharing gainz

**Comment by markspolakovs** [comment]
@michael-grace tbh in that case I'd personally prefer if it were on 2016-site, because I don't think there's precedent for publicly-human-visible MyRadio links (and it's a bit ugly imo)

**Comment by SplashyFish14** [comment]
I don't love this, but I suppose it's fine for now, would it be possible for it to be easily editable without doing a PR?

**Comment by SplashyFish14** [comment]
Ok, after more thonking, thoughts on having the page on the wiki and just linking to it for now? saves you writing bad code :P

**Comment by michael-grace** [comment]
...wonders why we didnt just think of a wiki page originally...


And its not **_bad_** code

**Comment by markspolakovs** [comment]
@michael-grace @SplashyFish14 can this be closed?

**Pull request closed without merging**
