### PR TITLE
Upgrade Vagrant to Ubuntu 19.04 / psql11

### PR DESCRIPTION
**Pull request by mstratford**
Also fixes the fact MyRadio can't configure it's own config file on Setup.
It also reloads apache2 on vagrant up, it seems to not load the config correctly otherwise.

### CODE REVIEW

**Comment by LordAro** [comment]
Would be good to sort the remaining CI issues while you're at it

**Comment by LordAro** [comment]
Went ahead and did it anyway :)

**Comment by mstratford** [comment]
Ok, tested this now on MacOS. Would like if someone else could check a new install on a different platform.

**Comment by markspolakovs** [comment]
@mstratford Tested on Ubuntu, seems to work fine

**Comment by mstratford** [comment]
Nice, well, I guess I can't approve it... so :)

**Pull request merged**
