### PR TITLE
Add getCurrentAndNextObjects and expose it to GraphQL

### PR DESCRIPTION
**Pull request by markspolakovs**
Because getCurrentAndNext is a pain in the arse to work with

### CODE REVIEW

**Comment by URY-GitHub** [comment]
Thank you for this pull request, @markspolakovs!

@SplashyFish14, would you mind reviewing this PR, please? Feel free to ask anyone for help if you're not quite sure what you're doing.

**Comment by markspolakovs** [comment]
Alice says no.

**Comment by michael-grace** [comment]
Why pseudo shows as well as timeslots?

**Comment by markspolakovs** [comment]
@michael-grace right, that should probably be PseudoTimeslot. Will change.

(Why: because if there's no show on, getCurrentAndNext returns a "pseudo-timeslot" for either Jukebox or Off Air.)

**Comment by markspolakovs** [comment]
@michael-grace Ready to test on https://ury.org.uk/api-staging/graphql?api_key=YOUR_API_KEY&query={currentAndNext{current{__typename,...%20on%20Timeslot%20{title}...%20on%20CurrentAndNext_PseudoTimeslot%20{title}}next{__typename,...%20on%20Timeslot%20{title}...%20on%20CurrentAndNext_PseudoTimeslot{title}}}}

or, unminified:
```graphql
{
  currentAndNext {
    current {
      __typename
      ... on Timeslot {
        title
      }
      ... on CurrentAndNext_PseudoTimeslot {
        title
      }
    }
    next {
      __typename
      ... on Timeslot {
        title
      }
      ... on CurrentAndNext_PseudoTimeslot {
        title
      }
    }
  }
}
```

**Comment by markspolakovs** [comment]
@michael-grace fixed in latest commit

**Pull request merged**
