### PR TITLE
Add WebStudio action and associated permissions

### PR DESCRIPTION
**Pull request by markspolakovs**
This PR adds an action to direct users to WebStudio.

I've already created an associated "WebStudio Trained" presenterstatus on prod, verified correct operation on Staging.

### CODE REVIEW

**Comment by mstratford** [comment]
Is it worth actually having a myradio controller for this? Webstudio already works out which timeslot you have selected...

**Comment by markspolakovs** [comment]
Yes, just for the sake of "go to myradio and click webstudio" instead of "go to myradio, select a timeslot, then type in this other URL"

**Comment by mstratford** [comment]
Oh yeah, I did mean to keep the button, but we don't need to put the timeslot_id in the URL anymore anyway. Could just link directly to /webstudio

**Comment by markspolakovs** [comment]
Ah, fair. The benefit of the controller is that we can use `CoreUtils::requireTimeslot();`, saving a redirect ping-pong of MyRadio->WebStudio->MyRadio->WebStudio

**Comment by mstratford** [comment]
Meh, fair. Maybe we just remove the timeslot_id from the URL, but still controller. Looks cleaner to user, and currently typing in a timeslot_id will make the show plan loaded not line up with the navbar data.

**Comment by markspolakovs** [comment]
Sure, let's do that.

**Pull request merged**
