### PR TITLE
Update YUSU membership payment link

### PR DESCRIPTION
**Pull request by wlcx**

### CODE REVIEW

**Comment by LordAro** [comment]
Don't suppose you could config it? :>

**Comment by wlcx** [comment]
no u

**Comment by wlcx** [comment]
no u

**Comment by wlcx** [comment]
That's way more convoluted though? Why do config->injected into javascript->some javascript somewhere which loads it into the DOM when we have a perfectly good templating system? This is more explicit and doesn't require JS which is always a plus in my view.

**Comment by LordAro** [comment]
because it's how it's done? by all means fix it in future, but it should be consistent with what we've got at the moment

**Comment by wlcx** [comment]
Ok, what ware you talking about here? Which js config file?

**Comment by LordAro** [comment]
My bad, i don't mean javascript at all, i mean the twig config object - https://github.com/UniversityRadioYork/MyRadio/blob/master/src/Classes/MyRadioTwig.php#L64 & https://github.com/UniversityRadioYork/MyRadio/blob/master/src/Classes/Config.php#L708

**Comment by wlcx** [comment]
Ok that makes more sense :p

**Comment by wlcx** [comment]
Updated

**Pull request merged**
