### PR TITLE
Lintmore

### PR DESCRIPTION
**Pull request by LordAro**
Foobar.

One thing I'm not sure about - both joyride js files appear to have a mysterious constant if condition - https://github.com/UniversityRadioYork/MyRadio/blob/master/src/Public/js/myury.joyride.first_show.js#L8 & https://github.com/UniversityRadioYork/MyRadio/blob/master/src/Public/js/myury.joyride.banner.js#L8

They've had that condition as long as the files have been in the repo, but I can't work out why at all. Just a typo?

### CODE REVIEW

**Comment by AJDurant** [comment]
Is {{action}} replaced somehow, or is it a template of an unfinished joyride? I don't really know anything about them @lloydw ?

**Comment by LloydW93** [comment]
I suspect the joyride files used to be in the Twig templates directly and is now broken from being moved out. But I remember basically nothing about them.

**Comment by LordAro** [comment]
I'll take them out since they apparently do nothing and haven't been needed anyway

(does joyride stuff even work anyway?)

**Comment by LordAro** [comment]
I couldn't find anything anywhere, I'm happy to be proved wrong though

**Pull request merged**
