### PR TITLE
Made the webcam archive page actually display a page.

### PR DESCRIPTION
**Pull request by mstratford**
Just thought I would make this page actually be a page, y'know.

### CODE REVIEW

**Comment by LordAro** [comment]
But what if i want to know what the current unix epoch is equal to?!

**Comment by mstratford** [comment]
Haha ;) Maybe i'll get around to seeing if I can actually build fully, but it would be nice to get a user friendly page :)

**Comment by LordAro** [comment]
But more seriously, not a fan of the commented out code. This is what we have version control systems for ;)

**Comment by mstratford** [comment]
Sorry, there you go :)

**Pull request merged**
