### PR TITLE
Make Show Plan Importer 100% API based.

### PR DESCRIPTION
**Pull request by mstratford**
Allows it to work with WebStudio with no URL query string param hacks.

### CODE REVIEW

**Comment by URY-GitHub** [comment]
Thank you for this pull request, @mstratford!

@michael-grace, would you mind reviewing this PR, please? Feel free to ask anyone for help if you're not quite sure what you're doing.

**Review by markspolakovs — APPROVED** [review]
I wouldn't mind an origin check, but there's not much damage you could do with just reloading the importer, so this is fine. I presume you've tested this?

**Comment by markspolakovs** [comment]
Whoops, didn't mean to review the entire PR there :p looks fine to me though

**Comment by mstratford** [comment]
> I wouldn't mind an origin check, but there's not much damage you could do with just reloading the importer, so this is fine. I presume you've tested this?

I came to the same conclusion, I'll see if wildcard origins are possible. It has indeed been tested (a lot) 👍

**Comment by mstratford** [comment]
Added an origin check, works 👍

**Pull request merged**
