### PR TITLE
Fix graphql api

### PR DESCRIPTION
**Pull request by ashhhleyyy**
Updates php-graphql (not necessary for the fix, but still good to have)
Fixes the TypeError on graphql queries

### CODE REVIEW

**Review by markspolakovs — COMMENTED** [review]
composer.lock?

**Comment by ashhhleyyy** [comment]
the repo doesn't have one?

**Review by markspolakovs — APPROVED** [review]
Indeed it doesn't, whoops. (Maybe it should, but that's a separate issue.)

LGTM, though I am slightly concerned by the jump from 0.13.8 to 15.0.0 (it's not as big as it looks - seemingly upstream went from 0.13 to 14.0 - but still a major bump). Have you had a chance to test the new version? 

Approving on the basis that you've tested it.

**Comment by ashhhleyyy** [comment]
I've tested with the currently failing queries from radioplayer and icetracks2, along with playing around in graphiql with other queries, and I didn't find anything to be broken - I've also had a skim-read through the changelog and for the two breaking releases (14.0.0 and 15.0.0) and didn't see anything that immediately stood out as being an issue

**Pull request merged**
