### PR TITLE
Allow marking "podcast shows" as explicit

### PR DESCRIPTION
**Pull request by markspolakovs**

### CODE REVIEW

**Comment by markspolakovs** [comment]
Tested creation and editing logic on dev, although for some reason the RSS API doesn't work on dev... hmm

**Comment by mstratford** [comment]
Looks good, if we’re changing the podcasting policy to allow explicit stuff, we’ll have to make that obvious in the embed player or whatever in 2016-site too.

**Comment by markspolakovs** [comment]
@mstratford it's always been allowed, policy just said "add a content warning to the description in bold". Could surface this in the UI, though.

**Comment by markspolakovs** [comment]
Hm, this appears to have surfaced a bug in MyRadio_Show::create... investigating

**Comment by markspolakovs** [comment]
Test's funky, need to figure out why. Works in staging, merging.

**Pull request merged**
