### PR TITLE
Don't trust API to return 3 channel if they're empty.

### PR DESCRIPTION
**Pull request by mstratford**
Importer wouldn't import properly if the show plan didn't have at least something in all three channels.

### CODE REVIEW

**Comment by URY-GitHub** [comment]
Thank you for this pull request, @mstratford!

@SplashyFish14, would you mind reviewing this PR, please? Feel free to ask anyone for help if you're not quite sure what you're doing.

**Review by markspolakovs — APPROVED** [review]
I have no idea what this does or how this works, but it kinda looks sane?

**Review by SplashyFish14 — COMMENTED** [review]
I have no idea what this does or how this works, but it kinda looks sane?

**Comment by mstratford** [comment]
Essentially I was just adding the 3 weights from the three channels of the show plan. But you don't get all 3 show plan channels if they're not filled with anything. So the importer just went "i don't have a weight for this channel" and didn't import.

**Pull request merged**
