### PR TITLE
Show message if no webcams setup.

### LINKED ISSUE #80: Notice if there are no webcams set up

### PR DESCRIPTION
**Pull request by mstratford**
Fixes #80

### CODE REVIEW

**Comment by markspolakovs** [comment]
Looks good, although can non-comp people see the webcams? Because if they can I'd change the wording to "if you're Computing check the database, if not ..."

**Comment by mstratford** [comment]
The message is aimed at computing, since it will only really appear on a fresh install with permissions set.

**Comment by markspolakovs** [comment]
That phpcs break is my fault, I promise I'll fix it...

**Comment by mstratford** [comment]
I've tested it on a new Vagrant box :)

**Pull request merged**
