### PR TITLE
Removed open on start feature of the SIS selector.

### PR DESCRIPTION
**Pull request by mstratford**
Closes UniversityRadioYork/Issues#63

### CODE REVIEW

**Comment by LordAro** [comment]
@LloydW93 any ideas why this was there in the first place?

**Comment by LloydW93** [comment]
Just a design decision between probably me/Andy at the time.

The Studio Selector used to be (still is?) limited to
- People with The Power
- People logged in from Studio 1

so it seemed reasonable for it to be there and open to be visible.

**Comment by AJDurant** [comment]
Or a copy paste mistake in making those panels.

I don't think the location thing is working properly, but it might be.

**Comment by mstratford** [comment]
@AJDurant Well, just tried with a non-comp member from my room, didn't show SIS selector or webcam, so I assume it works at least somewhat.

**Comment by AJDurant** [comment]
The permissions part works, not the location overriding said permissions
IIRC

**Comment by LordAro** [comment]
I mean the bit that opens it when `lastTime === 0` (which i'm not even sure of the meaning of, semantically)

(Not how it's open by default anyway)

**Comment by AJDurant** [comment]
Huh, I hadn't actually looked at it, only the emails... So lastTime is
updated each time a response is received on the long poll that ensures data
is kept in order. It would only ever be 0 on initialisation, before
receiving data, which would open it, but allow it to be closed. Not sure
why it was done like that.

**Comment by mstratford** [comment]
Am I correct in saying that this pr is ready for merge?

**Pull request merged**
