### PR TITLE
Expose tracklist to GraphQl

### PR DESCRIPTION
**Pull request by markspolakovs**

### CODE REVIEW

**Comment by URY-GitHub** [comment]
Thank you for this pull request, @markspolakovs!

@michael-grace, would you mind reviewing this PR, please? Feel free to ask anyone for help if you're not quite sure what you're doing.

**Comment by markspolakovs** [comment]
Tested, can be verified by going to https://ury.org.uk/api-dev/graphql?query={timeslot(itemid:146646){tracklist{itemId,startTime,track{artist,title,album{title}}}}}&api_key=YOUR_API_KEY_HERE

cc @michael-grace

**Comment by markspolakovs** [comment]
hrm, length parsing appears to be *janky*... investigating, but shouldn't block merging of this PR

**Comment by markspolakovs** [comment]
aaaaaargh... `MyRadio_TracklistItem::getTrack()` returns either a Track object (for track_rec) or an array (for track_notrec), which makes graphql go drunkaroo... although oddly only when you request `itemId` on the track

**Comment by michael-grace** [comment]
`{"errors":[{"message":"Cannot query field \"artist\" on type \"TracklistTrack\". Did you mean to use an inline fragment on \"Track\" or \"TrackNotRec\"?","extensions":{"category":"graphql"},"locations":[{"line":1,"column":59}]},{"message":"Cannot query field \"title\" on type \"TracklistTrack\". Did you mean to use an inline fragment on \"Track\" or \"TrackNotRec\"?","extensions":{"category":"graphql"},"locations":[{"line":1,"column":66}]},{"message":"Cannot query field \"album\" on type \"TracklistTrack\". Did you mean to use an inline fragment on \"Track\" or \"TrackNotRec\"?","extensions":{"category":"graphql"},"locations":[{"line":1,"column":72}]}]}`

**Comment by markspolakovs** [comment]
@michael-grace  Working on that, one sec...

**Comment by markspolakovs** [comment]
@michael-grace try https://ury.org.uk/api-dev/graphql?api_key=YOUR_API_KEY_HERE&debug=true&query={timeslot(itemid:%20146646){tracklist{itemId,track%20{...%20on%20Track%20{artist,title,album{title},clean,digitised,length},...%20on%20TrackNotRec%20{title,artist,albumName:%20album,trackno,length,record_label}},startTime}}}

**Pull request merged**
