### PR TITLE
Move timeslots

### PR DESCRIPTION
**Pull request by markspolakovs**
For years, PCs have been complaining about being unable to reschedule an episode, resorting to either database bodges or cancelling and creating a new season (which is bad because it deletes the showplan as well). This PR adds the ability to do that.

What it does not do is link to it anywhere, I still haven't figured out the best way of doing this. I'll sort that out later.

Test Plan:
* Deploy to dev
* Check that moving a show works properly

### CODE REVIEW

**Comment by LordAro** [comment]
Should really keep the formatting changes in a separate PR...

**Comment by markspolakovs** [comment]
Tested on dev, ready for review. *Vim on dev is a perfectly reasonable development method.*

**Comment by markspolakovs** [comment]
@LordAro damn it - I made those in a separate branch but forgot how Git works. Trouting is in order.

**Comment by markspolakovs** [comment]
and yes this will need a squash and merge.

**Comment by LordAro** [comment]
Sounds like something you should do locally - squash the commits into logical changes yourself ;)
There's no need for it to be all in 1 commit...

**Comment by markspolakovs** [comment]
I mean at this point the logical feature is "add this form and associated crapola", most of the in-between commits are fail and more fail, so a GitHub squash would do the trick

**Comment by LordAro** [comment]
Perhaps, but still - lots of this PR is arbitrary changes in formatting that should either be removed, or at least split into a (proper) separate commit. Makes it difficult to review!

**Comment by LordAro** [comment]
test comment, please ignore

**Comment by LordAro** [comment]
test comment, please ignore

**Comment by LordAro** [comment]
arbitrary comment

**Comment by LordAro** [comment]
arbitrary

**Comment by markspolakovs** [comment]
Matt, can you give this a skim before tomorrow's meeting? Quite a bit of the PR is formatting changes, sorry about that.

**Pull request merged**
