### PR TITLE
Check selector to display currentAndNext off-air vs Jukebox

### PR DESCRIPTION
**Pull request by markspolakovs**

### CODE REVIEW

**Comment by markspolakovs** [comment]
Verified on Staging:
image

**Comment by michael-grace** [comment]
do we want to do it this way, or change the `isTerm` function this (and potentially other stuff) references??

**Comment by Joseph-S12** [comment]
Given most of the summer is (this and potentially future years) a 'term' it is probably better to use this over isTerm.

**Comment by markspolakovs** [comment]
> do we want to do it this way, or change the `isTerm` function this (and potentially other stuff) references??

actually nothing else uses `isTerm()`, lol (in myradio itself at least, not sure about the API).

**Review by Joseph-S12 — APPROVED** [review]
I can't really test it, but as HoC, I am happy for it to 'go live' if you have tested it.

**Pull request merged**
