### PR TITLE
Navbar styling update

### PR DESCRIPTION
**Pull request by Brookke**
- Added logo
- set colour

See what you think

Closes: #585

### CODE REVIEW

**Comment by Brookke** [comment]
@ChrisTheBaron @sophiekinley can you take a look at this please and let me know what you think please 😄

**Comment by LordAro** [comment]
Did you check that the burger menu still works on mobiles?

**Comment by Brookke** [comment]
screen shot 2016-10-24 at 19 44 54

**Comment by Brookke** [comment]
I can't create an account on my local my radio so I can't fully test. If someone could explain or test this for me that'd be great 👍  Thanks

**Comment by LordAro** [comment]
It looks fine, but I'm inclined to agree with @LloydW93 on this - MyRadio isn't the website, so it shouldn't look the same. I'm all for a reskin if you feel that's necessary though

**Comment by LordAro** [comment]
Gonna close this until we can come to some conclusion over styling. Might even want to talk to DCM or others :o

**Comment by mstratford** [comment]
Just to comment here, tried it on my local account, however you managed to embed the text into the SVG image, the font doesn't carry over. Defaults to times new roman (or similar).

**Comment by AJDurant** [comment]
If you use a font in an svg it had to be available to the end user, or you
need to convert it to a path. The font used to be in the stylesheet, it may
just not match the right name.

**Pull request closed without merging**
