### PR TITLE
Make WebStudio training count as "studio demoed"

### PR DESCRIPTION
**Pull request by markspolakovs**
Also don't hardcode IDs in the code because that's silly

### CODE REVIEW

**Comment by URY-GitHub** [comment]
Thank you for this pull request, @markspolakovs!

@SplashyFish14, would you mind reviewing this PR, please? Feel free to ask anyone for help if you're not quite sure what you're doing.

**Review by SplashyFish14 — COMMENTED** [review]
Can't see anything wrong with it, apart from I don't like the name of the isStudioDemoed() function, doesn't really tell you what the function is doing, but that's just me being picky.

**Comment by markspolakovs** [comment]
@SplashyFish14 me neither, but this is Old Code (like, 2014 old)...

**Review by SplashyFish14 — APPROVED** [review]

**Review by michael-grace — APPROVED** [review]
LGTM

**Comment by markspolakovs** [comment]
Travis CI is a pile of donkey shit and builds are taking eons to queue up. I think it's time we migrated to GH Actions... Merging.

**Comment by michael-grace** [comment]
> Travis CI is a pile of donkey shit and builds are taking eons to queue up. I think it's time we migrated to GH Actions... Merging.

Yes.

**Pull request merged**
