### PR TITLE
Fix Mixclouder breakage due to API expecting POST request for setMeta

### PR DESCRIPTION
**Pull request by adfw**
As above.

### CODE REVIEW

**Comment by AJDurant** [comment]
Surely this should be a change on mixclouder, set commands should really be POST requests

**Comment by adfw** [comment]
Mixclouder would need much more refactoring compared to setting this attribute, as it has no concept of "What API request am I sending", it just sends them

**Comment by CaptainHayashi** [comment]
Looks fine to me (well, about as fine as comments with non-obvious semantic value can be), but I'll defer to @AJDurant with regards to approval.

**Comment by AJDurant** [comment]
It should be relatively easy to get mixclouder to use a post method though?
Any library that lets you send http will let you set the method.
I don't really like this as a 'fix'

**Comment by adfw** [comment]
Fixed in mixclouder - uses post, tested working. This commit now addresses a documentation issue for the getOptionsAllow function.

**Pull request merged**
