### PR TITLE
Fix Show Planner scroll

### PR DESCRIPTION
**Pull request by LordAro**

### CODE REVIEW

**Comment by LloydW93** [comment]
How'd you come up with 280px?

**Comment by LordAro** [comment]
arbitrary :)

**Comment by AJDurant** [comment]
Overflow hidden should be there, just not for the uploader

**Comment by LordAro** [comment]
It broke more things than it fixed, i think it needs a different solution, if indeed it's needed at all, i believe decreasing the minimum height to such a level should fix the "jumpiness" of show planner described in the original issue. Certainly stuff going off the bottom of the screen (like progress bars, play buttons, etc) should never be unclickable just because your screen isn't big enough

**Comment by LloydW93** [comment]
I guess this'll do for now, but tbh some proper responsive CSS should be done around height - below a certain screen height enable the scroll bar.

**Comment by LloydW93** [comment]
If you're happy, I'm happy.

**Pull request merged**
