### PR TITLE
Edit track form and functionality

### PR DESCRIPTION
**Pull request by AJDurant**
This doesn't currently have an easy way to access it, but I'm not sure when I'll be able to finish that and it would probably still be helpful to have now. you can access with editTrack?trackid=XXXX

### CODE REVIEW

**Comment by mstratford** [comment]
Fixes #354

**Comment by mstratford** [comment]
If the track is loaded into Show Planner, then after After changing a track using this form, the outputs of the Central Music Library do show up when searching for the new track name, but the old track name is the one listed.
http://imgur.com/a/Wz59T

**Comment by mstratford** [comment]
Also, before this goes available to all (with permissions), you may want to make it play nice with an empty trackid :)

**Comment by AJDurant** [comment]
Hehe that first one is fun, there'll be a dirty cache entry.

**Comment by LloydW93** [comment]
Could be related to #612

**Comment by mstratford** [comment]
Just tried on MyRadio-dev, doesn't look like the Caching problem can be replicated, so looks ready to merge.

**Comment by mstratford** [comment]
Seems ready to merge.

**Comment by AJDurant** [comment]
The cache may be (and I'm pretty sure is) turned off on the -dev branch

**Comment by mstratford** [comment]
I'll put it on my todo list 👍 I'll get round to it sooner rather than later.

**Comment by AJDurant** [comment]
I think someone asked me if I approve this, I do but I can't formally review on here because it's my PR

**Comment by mstratford** [comment]
There you go 👍

**Pull request merged**
