### PR TITLE
Vagrant

### PR DESCRIPTION
**Pull request by Flump5281**

### CODE REVIEW

**Comment by CaptainHayashi** [comment]
Seemed to work for me.

**Comment by LordAro** [comment]
needs a rebase, but can be merged?

**Comment by Flump5281** [comment]
Yis

**Comment by Flump5281** [comment]
Rebased and ready to merge.

**Comment by AJDurant** [comment]
This needs to go into master not bootstrap

**Comment by Flump5281** [comment]
Oh, whoops.

**Pull request merged**
