### PR TITLE
Removed columns that don't format nicely.

### PR DESCRIPTION
**Pull request by mstratford**

### CODE REVIEW

**Comment by AJDurant** [comment]
Could you not make them format nicely?

**Comment by mstratford** [comment]
I could, but at least the clean column having a 1 doesn't mean that it's clean... It's broken somehow...

**Comment by mstratford** [comment]
I'd kind of like to merge this soon, since otherwise it's lying to you ;P

**Comment by mstratford** [comment]
The album was output as an Array, not sure how to make it display nicely? I couldn't work out what it was an array of, but it looks like your (current live, not PR one) edit form also stays empty.

**Comment by AJDurant** [comment]
Hmm, interesting

**Pull request merged**
